version: "3.9"

services:
  server:
    build: .
    container_name: nodejs_server
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - GANACHE_URL=http://host.docker.internal:7545
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - avatar_net

networks:
  avatar_net:
    driver: bridge
